services:
  postgres:
    image: postgres:17
    container_name: taskhub-postgres

    environment:
      POSTGRES_USER: taskhub
      POSTGRES_PASSWORD: taskhub
      POSTGRES_DB: taskhub

    ports:
      - "5432:5432"

    volumes:
      - taskhub_postgres_data:/var/lib/postgresql/data

volumes:
  taskhub_postgres_data:
